In [1]:
from IPython.core.display import HTML
table_css = 'table {align:left;display:block} '
HTML('<style>{}</style>'.format(table_css))

# **ASI WA Python Workshop**

## **Jupyter Notebook Tips**

Outside of a cell:

| key combo | action |
| :--: | ---- |
| shift+enter |  run a cell |
| b |  insert cell below | 
| a |  insert cell above |
| dd | delete selected cell |

<br>
Within a cell:

| key combo | action |
| :--: | ---- |
| Command + / |  comment out line(s) |
| Alt + Cursor | vertical selection |

**Control = Command
<br><br><br>

---
<a id='1.1'></a>

<br>

**I have taken most of the content for this notebook from the individuals listed below, but I have edited it for clarity and added content that I believe you will find more useful.**
<br><br>

---
<a id='1.1'></a>

Author: Nicolai Riis, DTU Compute, July 2017.

### Licence:
These notebooks are released under the Attribution 3.0 Unported Licence (https://creativecommons.org/licenses/by/3.0/). This means you are free to share and adapt the content as you please as long as you give appropriate credit, link the licence and indicate if changes are made to the material.

For the original content that these notebooks are based upon please see:

* https://github.com/jhamrick/nbgrader-demo/tree/master/instructor/source/ps1
* https://github.com/jrjohansson/scientific-python-lectures


---
<a id='1.1'></a>

# **NumPy**
NumPy, short for Numerical Python, is a widely-used Python package for numerical computations. It is so popular it is considered part of the Python trinity (NumPy, Pandas, MatPlotLib). It provides high-performance data structures for handling arrays of numbers, such as vectors and matrices. Under the hood, numpy is programmed in C and Fortran, making it super fast.

When using NumPy, we just need to import the module as we've done before. However, since it's so popular, people often use the shorthand `np` to refer to `numpy` for convenience. So, instead of writing `numpy.function()`, we can simply write `np.function()`.

In [4]:
import numpy as np

NumPy is incredibly powerful and has many features, but this can be a bit intimidating when you're first starting to use it. If you are familiar with other scientific computing languages, the following guides may be of use:
* NumPy for Matlab Users: http://mathesaurus.sourceforge.net/matlab-numpy.html
* NumPy for R (and S-Plus) Users: http://mathesaurus.sourceforge.net/r-numpy.html

If not, don't worry! Here we'll go over the most common NumPy features.

---
<a id='2.1'></a>

## **Arrays**
The core component of NumPy is the `ndarray`, which is pronounced like "N-D array" (i.e., 1-D, 2-D, ..., N-D). We'll use both the terms `ndarray` and "array" interchangeably. For now, we're going to stick to just 1-D arrays -- we'll get to multidimensional arrays later.

Arrays are very similar to `lists`. Let's first review how lists work. Remember that we can create them using square brackets:

In [19]:
mylist = [3, 6, 1, 0, 10, 3]
mylist

[3, 6, 1, 0, 10, 3]

And we can access an element via its *index*. To get the first element, we use an index of 0:

In [20]:
print("The first element of 'mylist' is: " + str(mylist[0]))

The first element of 'mylist' is: 3


To get the second element, we use an index of 1:

In [21]:
print("The second element of 'mylist' is: " + str(mylist[1]))

The second element of 'mylist' is: 6


And so on.

Arrays work very similarly. The first way to create an array is from an already existing list:

In [22]:
myarray = np.array(mylist) # equivalent to np.array([3, 6, 1, 0, 10, 3])
myarray

array([ 3,  6,  1,  0, 10,  3])

<div class="alert alert-info">
Notice that <code>myarray</code> looks different than <code>mylist</code> -- it actually tells you that it's an array. If we take a look at the <i>types</i> of <code>mylist</code> and <code>myarray</code>, we will also see that one is a list and one is an array. Using <code>type</code> can be a very useful way to verify that your variables contain what you want them to contain:
</div>

In [25]:
# look at what type mylist is
type(mylist)

list

In [26]:
# look at what type myarray is
type(myarray)

numpy.ndarray

We can get elements from a NumPy array in exactly the same way as we get elements from a list:

In [27]:
print("The first element of 'myarray' is: " + str(myarray[0]))
print("The second element of 'myarray' is: " + str(myarray[1]))

The first element of 'myarray' is: 3
The second element of 'myarray' is: 6


The numpy.ndarray may initially resemble a Python list or nested list. You might wonder why we need a new array type instead of just using Python lists for computations.

Here are a few reasons:
- Python lists are quite versatile and can hold any kind of object. However, they lack built-in support for mathematical functions like matrix and dot multiplications.
- Numpy arrays, on the other hand, are specifically designed for numerical computations. They are statically typed and ensure that the elements have a consistent type throughout the array.
- Numpy arrays are also memory efficient, providing better performance and reducing memory overhead compared to Python lists.

By utilizing the dtype (data type) property of an ndarray, we can easily identify the type of data stored within the array.

In [12]:
myarray.dtype

dtype('int64')

### Methods for Arrays  

Like `range()` for a list, we can generate an array with regularly spaced values within a specified range

In [29]:
# create a range
x = np.arange(0, 10, 1) # arguments: start, stop, step
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

A useful function for plotting mathematical functions is "linespace". Linespace returns evenly spaced numbers over a specified interval. We specify the starting point of the sequence and the ending point of the sequence. The parameter "num" indicates the Number of samples to generate:

In [33]:
# using linspace, both end points ARE included
np.linspace( start=0, stop=10, num=10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

One thing that you can do with lists that you *cannot* do with NumPy arrays is adding and removing elements. For example, I can create a list and then add elements to it with `append`:

In [37]:
mylist = []
mylist.append(7)
mylist.append(2)
mylist

[7, 2]

However, you *cannot* do this with NumPy arrays. If you tried to run the following code, for example:

```python
myarray = np.array([])
myarray.append(7)
```

You'd get an error like this:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-25-0017a7f2667c> in <module>()
      1 myarray = np.array([])
----> 2 myarray.append(7)

AttributeError: 'numpy.ndarray' object has no attribute 'append'
```

---
<a id='2.1'></a>

**NumPy arrays prioritize speed and efficiency over the flexibility of Python lists.**

---
<a id='2.1'></a>

<div class="alert alert-info">To create a NumPy array, you must create an array with the correct shape <i>from the beginning</i>. However, the array doesn't have to have all the correct values from the very beginning: these you can fill in later.</div>

This is generally not a problem, we can almost always work out what the size or shape of the array needs to be. 

There are a few ways to create a new array with a particular shape:

* `np.empty(shape)` -- creates an empty array of shape `shape`
* `np.zeros(shape)` -- creates an array of shape `shape` and sets all the elements to zero
* `np.ones(shape)` -- creates an array of shape `shape` and sets all the elements to one


In [38]:
arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

<div class="alert alert-info">
The *shape* of the array is a very important concept. You can always get the shape of an array by accessing its <code>shape</code> attribute:
</div>

In [39]:
arr.shape

(3, 4)

Note that for 1-D arrays, the shape returned by the `shape` attribute is still a tuple, even though it only has a length of one:

In [40]:
np.zeros(3).shape

(3,)

This also means that we can *create* 1-D arrays by passing a length one tuple. Thus, the following two arrays are identical:

In [41]:
np.zeros((3,))

array([0., 0., 0.])

In [42]:
np.zeros(3)

array([0., 0., 0.])

<div class="alert alert-danger">There is a warning that goes with this, however: be careful to always use tuples to specify the shape when you are creating multidimensional arrays. For example, to create an array of zeros with shape <code>(3, 4)</code>, we <b>must</b> use <code>np.zeros((3, 4))</code>. The following <b>will not work</b>:</div>

```python
np.zeros(3, 4)
```

It will give an error like this:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-39-06beb765944a> in <module>()
----> 1 np.zeros(3, 4)

TypeError: data type not understood
```

This is because the second argument to `np.zeros` is the data type, so numpy thinks you are trying to create an array of zeros with shape `(3,)` and datatype `4`. It (understandably) doesn't know what you mean by a datatype of `4`, and so throws an error.

<div class="alert alert-info">
Another important concept is the <i>size</i> of the array -- in other words, how many elements are in it. This is equivalent to the length of the array, for 1-D arrays, but not for multidimensional arrays. You can also see the total size of the array with the <code>size</code> attribute:
</div>

In [44]:
arr = np.zeros((3, 4))
arr.size

12

We can also create arrays and then reshape them into any shape, provided the new array has the same size as the old array:

In [45]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

#### *Task 5.1: Creating NumPy Arrays*

1. Create a NumPy array using np.linspace to generate a sequence of 11 evenly spaced values between 0 and 100.

2. Create an empty NumPy 1D array with a size of 7 using np.empty and print the size

3. Create a NumPy array of shape 5x5 filled with ones using np.ones and print the shape of the array.

4. Create a NumPy array of shape 4x6 filled with zeros using np.zeros and reshape it to 8x3. Print the shape before and after reshaping. 

In [73]:
# Task 5.1



---
### Math Functions

Example of how you would add a scaler to a 2d list:

In [56]:
lst = [[1, 2, 3], 
       [4, 5, 6]] # 2d array

for row_idx, row_val in enumerate(lst):
    for col_idx, col_val in enumerate(row_val):
        lst[row_idx][col_idx] += 1
lst

[[2, 3, 4], [5, 6, 7]]

We can accomplish the same using NumPy's ufunc for element-wise scalar addition as shown below:

In [60]:
ary = np.array([[1, 2, 3], [4, 5, 6]])
ary = ary + 1
ary

array([[2, 3, 4],
       [5, 6, 7]])

All NumPy operators perform element wise operations (`+`, `-`, `/`, `*`, and `**`):

In [63]:
ary**2

array([[ 4,  9, 16],
       [25, 36, 49]])

NumPy also has implementations of several useful functions, such as `log` (natural logarithm), `log10` (base-10 logarithm), and `sqrt` (square root):

In [64]:
np.sqrt(ary)

array([[1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131]])

In [66]:
np.log10( [1, 10, 100, 1e3, 1e4, 1e5])

array([0., 1., 2., 3., 4., 5.])

In [67]:
np.sin( [0,1,2,3])

array([0.        , 0.84147098, 0.90929743, 0.14112001])

#### *Task 5.2: Task: Array Manipulation with Addition and Multiplication*

1. Create a NumPy array of your choice with desired values.

2. Add a scaler, such as 5, to your array from step 1.

3. Create another NumPy array with desired values.

4. Multiply arrays from step 1 and step 3.

In [75]:
# Task 5.2



#### *Task 5.3 Rewrite the licode below using numpy*
```
from math import sin, cos
import matplotlib.pyplot as plt

# generate interval of points in a list
interval = range( 0, 50, 1)
# get sine values
y1 = []
x1 = []
for ii in interval: 
    y1.append(sin(ii))
    x1.append(cos(ii))

# call the plt package and 
plt.plot(x1, y1)
# tell matplotlib to produce the plot
plt.show()
```

In [ ]:
# Task 5.3



---
### Reduction Functions
Reduction Functions perform operations on an array or matrix and reduce it to a single value or an array of values based on a specified axis.

In [43]:
ary.sum(axis=0) # column sums

array([5, 7, 9])

In [44]:
ary.sum(axis=1) # row sums

array([ 6, 15])

As a word of caution, keep in mind that `product` and `sum` both compute the product or sum of the entire array if we do not specify an axis:

In [45]:
ary.sum()

21

Other useful unary ufuncs are:
    
- `np.mean` (computes arithmetic mean or average)
- `np.std` (computes the standard deviation)
- `np.var` (computes variance)
- `np.sort` (sorts an array)
- `np.argsort` (returns indices that would sort an array)
- `np.min` (returns the minimum value of an array)
- `np.max` (returns the maximum value of an array)
- `np.argmin` (returns the index of the minimum value)
- `np.argmax` (returns the index of the maximum value)
- `np.array_equal` (checks if two arrays have the same shape and elements)

### Random Data

In [47]:
from numpy import random

In [48]:
# uniform random numbers from 0 to 1
random.rand(5,5)

array([[0.83847084, 0.9417874 , 0.72440674, 0.46426615, 0.6615207 ],
       [0.35277844, 0.61841712, 0.88060351, 0.09895485, 0.9675913 ],
       [0.26583841, 0.54166466, 0.97545221, 0.12317807, 0.84881773],
       [0.11215718, 0.13618037, 0.56379913, 0.66605392, 0.03127216],
       [0.6123945 , 0.50712066, 0.10927725, 0.78279931, 0.11255034]])

In [49]:
# standard normal distributed random numbers
random.randn(5,5)

array([[ 0.43884302, -0.66385851,  1.71373657, -0.6362204 ,  0.58923788],
       [ 0.12185815,  1.02767693,  1.03703313,  0.9124016 , -0.35478422],
       [-4.06991596, -0.19745311, -1.21548923,  1.18187005,  1.06011796],
       [ 0.9844759 ,  0.33032078, -0.56388684,  0.4876717 ,  0.01060864],
       [ 1.74681893, -0.25875905,  0.52113055, -0.3383865 , -0.81563693]])

In [55]:
# numpy random contains many types of distributions
random.negative_binomial( n=5, p=0.25, size=10)

array([15, 15, 18,  8, 18, 12, 23, 14, 17, 14])

## Accessing and modifying multidimensional array elements

To access or set individual elements of the array, we can index with a sequence of numbers:

In [ ]:
# set the 3rd element in the 1st row to 0
arr[0, 2] = 0
arr

We can also access the element on it's own, without having the equals sign and the stuff to the right of it:

In [ ]:
arr[0, 2]

We frequently will want to access ranges of elements. In NumPy, the first dimension (or *axis*) corresponds to the rows of the array, and the second axis corresponds to the columns.

<div class="alert alert-warning">Note: be careful about setting modifying an array if what you really want is a <i>copy</i> of an array. Remember that in Python, variables are really just pointers to objects.</div>

For example, if I want to create a second array that mutliples every other value in `arr` by two, the following code will work but will have unexpected consequences:

In [ ]:
arr = np.arange(10)
arr2 = arr
arr2[::2] = arr2[::2] * 2
print("arr:  " + str(arr))
print("arr2: " + str(arr2))

Note that `arr` and `arr2` both have the same values! This is because the line `arr2 = arr` doesn't actually copy the array: it just makes another pointer to the same object. To truly copy the array, we need to use the `.copy()` method:

In [ ]:
arr = np.arange(10)
arr2 = arr.copy()
arr2[::2] = arr2[::2] * 2
print("arr:  " + str(arr))
print("arr2: " + str(arr2))

## Indexing

<div class="alert alert-info">Also like lists, we can use "slicing" to get different parts of the array. Slices look like
<code>myarray[a:b:c]</code>, where <code>a</code>, <code>b</code>, and <code>c</code> are all optional (though you have to specify at least one). <code>a</code> is the index of the beginning of the slice, <code>b</code> is the index of the end of the slice (exclusive), and <code>c</code> is the step size.
</div>

Note that the exclusive slice indexing described above is different than some other languages you may be familiar with, like Matlab and R. `myarray[1:2]` returns only the second elment in myarray in Python, instead of the first and second element. 

First, let's quickly look at what is in our array (defined above), for reference:

In [ ]:
print("myarray:", myarray)

Now, to get all elements except the first:

In [ ]:
myarray[1:]

To get all elements except the last:

In [ ]:
myarray[:-1]

To get all elements except the first and the last:

In [ ]:
myarray[1:-1]

To get every other element of the array (beginning from the *first* element):

In [ ]:
myarray[::2]

To get every element of the array (beginning from the *second* element):

In [ ]:
myarray[1::2]

And to reverse the array:

In [ ]:
myarray[::-1]

Index slicing works exactly the same way for multidimensional "Matrix" arrays:

In [ ]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])

A

In [ ]:
# a block from the original array
A[1:4, 1:4]

In [ ]:
# strides
A[::2, ::2]

---
<a id='2.1'></a>

## 2.2 Vectorized computation

Vectorizing code is the key to writing efficient numerical calculation with Python/Numpy. That means that as much as possible of a program should be formulated in terms of matrix and vector operations, like matrix-matrix multiplication.

### Scalar-array operations

One advantage of using NumPy arrays over lists is the ability to do a computation over the entire array. For example, if you were using lists and wanted to add one to every element of the list, here's how you would do it:

In [ ]:
mylist = [3, 6, 1, 0, 10, 22]
mylist_plus1 = []
for x in mylist:
    mylist_plus1.append(x + 1)
mylist_plus1

Or, you could use a list comprehension:

In [ ]:
mylist = [3, 6, 1, 0, 10, 22]
mylist_plus1 = [x + 1 for x in mylist]
mylist_plus1

In contrast, adding one to every element of a NumPy array is far simpler:

In [ ]:
myarray = np.array([3, 6, 1, 0, 10, 22])
myarray_plus1 = myarray + 1
myarray_plus1

This won't work with normal lists. For example, if you ran `mylist + 1`, you'd get an error like this:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-5b3951a16990> in <module>()
----> 1 mylist + 1

TypeError: can only concatenate list (not "int") to list
```

We can do the same thing for subtraction, multiplication, etc.:

In [ ]:
print("Subtraction: \t" + str(myarray - 2))
print("Multiplication:\t" + str(myarray * 10))
print("Squared: \t" + str(myarray ** 2))
print("Square root: \t" + str(np.sqrt(myarray)))
print("Exponential: \t" + str(np.exp(myarray)))

### Working with multiple arrays

We can also easily do these operations for multiple arrays. For example, let's say we want to add the corresponding elements of two lists together. Here's how we'd do it with regular lists:

In [ ]:
list_a = [1, 2, 3, 4, 5]
list_b = [6, 7, 8, 9, 10]
list_c = [list_a[i] + list_b[i] for i in range(len(list_a))]
list_c

With NumPy arrays, we just have to add the arrays together:

In [ ]:
array_a = np.array(list_a) # equivalent to np.array([1, 2, 3, 4, 5])
array_b = np.array(list_b) # equivalent to np.array([6, 7, 8, 9, 10])
array_c = array_a + array_b
array_c

<div class="alert alert-warning">
Note: make sure when adding arrays that you are actually working with arrays, because if you try to add two lists, you will *not* get an error. Instead, the lists will be concatenated:
</div>

In [ ]:
list_a + list_b

Just as when we are working with a single array, we can add, subtract, divide, multiply, etc. several arrays together:

In [ ]:
print("Subtraction: \t" + str(array_a - array_b))
print("Multiplication:\t" + str(array_a * array_b))
print("Exponent: \t" + str(array_a ** array_b))
print("Division: \t" + str(array_a / array_b))

Another very useful thing about NumPy is that it comes with many so-called "vectorized" operations. A vectorized operation (or computation) works across the entire array. For example, let's say we want to add together all the numbers in a list. In regular Python, we might do it like this:

In [ ]:
mylist = [3, 6, 1, 10, 22]
total = 0
for number in mylist:
    total += number
total

Using NumPy arrays, we can just use the `np.sum` function:

In [ ]:
# you can also just do np.sum(mylist) -- it converts it to an
# array for you!
myarray = np.array(mylist)
np.sum(myarray)

<div class="alert alert-info">
There are many other vectorized computations that you can do on NumPy arrays, including multiplication (<code>np.prod</code>), mean (<code>np.mean</code>), and variance (<code>np.var</code>). They all act essentially the same way as <code>np.sum</code> -- give the function an array, and it computes the relevant function across all the elements in the array.
</div>

As mentioned several times by now, to get good performance we should try to avoid looping over elements in our vectors and matrices, and instead use vectorized algorithms. The first step in converting a scalar algorithm to a vectorized algorithm is to make sure that the functions we write work with vector inputs.

In [ ]:
def Theta(x):
    """
    Scalar implemenation of the Heaviside step function.
    """
    if x >= 0:
        return 1
    else:
        return 0

In [ ]:
Theta(np.array([-3,-2,-1,0,1,2,3]))

OK, that didn't work because we didn't write the `Theta` function so that it can handle a vector input... 

To get a vectorized version of Theta we can use the Numpy function `vectorize`. In many cases it can automatically vectorize a function:

In [ ]:
Theta_vec = np.vectorize(Theta)

In [ ]:
Theta_vec(np.array([-3,-2,-1,0,1,2,3]))

We can also implement the function to accept a vector input from the beginning (requires more effort but might give better performance):

In [ ]:
def Theta(x):
    """
    Vector-aware implemenation of the Heaviside step function.
    """
    return 1 * (x >= 0)

In [ ]:
Theta(np.array([-3,-2,-1,0,1,2,3]))

In [ ]:
# still works for scalars as well
Theta(-1.2), Theta(2.6)

---
<a id='2.1'></a>

## 2.4 Exercises

### Exercise 1: Euclidean distance (2 points)

Recall that the Euclidean distance $d$ is given by the following equation:

$$
d(a, b) = \sqrt{\sum_{i=1}^N (a_i - b_i) ^ 2}
$$

In NumPy, this is a fairly simple computation because we can rely on array computations and the `np.sum` function to do all the heavy lifting for us.

<div class="alert alert-success">
Complete the function <code>euclidean_distance</code> below to compute $d(a,b)$, as given by the equation above. Note that you can compute the square root using <code>np.sqrt</code>.
</div>

In [ ]:
def euclidean_distance(a, b):
    """Computes the Euclidean distance between a and b.
    
    Hint: your solution can be done in a single line of code!
    
    Parameters
    ----------
    a, b : numpy arrays or scalars with the same size
    
    Returns
    -------
    the Euclidean distance between a and b
    
    """
    # YOUR CODE HERE
    raise NotImplementedError()

<div class="alert alert-warning">Remember that you need to execute the cell above (with your definition of <code>euclidean_distance</code>), and then run the cell below to check your answer. If you make changes to the cell with your answer, you will need to <i>first</i> re-run that cell, and <i>then</i> re-run the test cell to check your answer again.</div>

In [ ]:
# add your own test cases in this cell!


In [ ]:
from nose.tools import assert_equal, assert_raises

# check euclidean distance of size 3 integer arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
assert_equal(euclidean_distance(a, b), 5.196152422706632)

# check euclidean distance of size 4 float arrays
x = np.array([3.6, 7., 203., 3.])
y = np.array([6., 20.2, 1., 2.])
assert_equal(euclidean_distance(x, y), 202.44752406487959)

# check euclidean distance of scalars
assert_equal(euclidean_distance(1, 0.5), 0.5)

# check that an error is thrown if the arrays are different sizes
a = np.array([1, 2, 3])
b = np.array([4, 5])
assert_raises(ValueError, euclidean_distance, a, b)
assert_raises(ValueError, euclidean_distance, b, a)

print("Success!")

### Exercise 2: Border (3 points)

<div class="alert alert-success">
Write a function to create a 2D array of arbitrary shape. This array should have all zero values, except for the elements around the border (i.e., the first and last rows, and the first and last columns), which should have a value of one.
</div>

In [ ]:
def border(n, m):
    """Creates an array with shape (n, m) that is all zeros
    except for the border (i.e., the first and last rows and
    columns), which should be filled with ones.

    Hint: you should be able to do this in three lines
    (including the return statement)

    Parameters
    ----------
    n, m: int
        Number of rows and number of columns

    Returns
    -------
    numpy array with shape (n, m)

    """
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
# add your own test cases in this cell!

In [ ]:
from numpy.testing import assert_array_equal
from nose.tools import assert_equal

# check a few small examples explicitly
assert_array_equal(border(1, 1), [[1]])
assert_array_equal(border(2, 2), [[1, 1], [1, 1]])
assert_array_equal(border(3, 3), [[1, 1, 1], [1, 0, 1], [1, 1, 1]])
assert_array_equal(border(3, 4), [[1, 1, 1, 1], [1, 0, 0, 1], [1, 1, 1, 1]])

# check a few large and random examples
for i in range(10):
    n, m = np.random.randint(2, 1000, 2)
    result = border(n, m)

    # check dtype and array shape
    assert_equal(result.dtype, np.float)
    assert_equal(result.shape, (n, m))

    # check the borders
    assert (result[0] == 1).all()
    assert (result[-1] == 1).all()
    assert (result[:, 0] == 1).all()
    assert (result[:, -1] == 1).all()

    # check that everything else is zero
    assert np.sum(result) == (2*n + 2*m - 4)

print("Success!")